### ISSUE TITLE
BeaconManager is almost never bound on resume

### ISSUE THREAD

**Issue by samskiter** [AltBeacon/android-beacon-library-reference#10]
In the ranging activity example onResume is called very shortly after onCreate, meaning the BeaconManager has not yet received an onServiceConnected message, which in turn means `isBound` always returns false which means the manager always stays in background mode

**Comment by samskiter** [comment]
A bit more information...

Commenting out the 'regionBootstrap' from the application object will cause `isBound` to always be false in `onResume` of the RegionActivity - rotating the activity will prove this. The app will then generate an error when the RangingActivity is rotated:

>Cannot contact service to set scan periods

This is the backgroundPowerSaver trying to set the backgroundMode.
The scan periods do get through however as the background power saver manages to flip the background flag, allowing the `startRangingBeaconsInRegion` call to get through and use the new values.

If we therefore remove the backgroundPowerSaver from the application, the RangingActivity ends up using the background scan periods (5 minutes) after a rotate.

**Comment by davidgyoung** [comment]
Good point.  The BackgroundPower saver was really designed to be in use along with the RegionBootstrap, although this is not explicitly stated in documentation and nothing enforces this.  At a minimum this should be documented.

**Comment by samskiter** [comment]
I actually didn't intend to use region bootstrap in my application, but I'll need to put an empty implementation in?

It seems that with neither the backgroundPowerSaver or the region bootstrap, I will get in trouble in rotates and always be in background mode. With just the background backgroundPowerSaver I'll be ok, but get a warning and with both I'll be ok, no warnings.

**Comment by davidgyoung** [comment]
If you disable both the RegionBootstrap and the BackgroundPowerSaver then everything should work okay.  The default state when not using the BackgroundPowerSaver is foreground mode.  So it really doesn't matter if the isBound is still false the first time onResume() is called.

**Comment by samskiter** [comment]
But the activity sets the background mode in the onPause/onResume. Following a rotate, the acitivity will be remade and so will the service. ServiceMessenger will be null in the BeaconManager so the isBound() check will fail, leaving the beaconmanager in background mode.

**Comment by davidgyoung** [comment]
Understood.  Here is a proposed fix: https://github.com/AltBeacon/android-beacon-library/pull/214
