### ISSUE TITLE
No idea how to use this app

### ISSUE THREAD

**Issue by ericntd** [AltBeacon/android-beacon-library-reference#13]
I can run this app without any error on my Nexus 5 (Android 5.1.0).
However, I have no idea how to use it. It's nothing like https://play.google.com/store/apps/details?id=com.radiusnetworks.locate&hl=en which can detect my beacon

**Comment by davidgyoung** [comment]
This app by default will only detect beacons transmitting the open source AltBeacon standard.  You can easily modify it to detect proprietary beacons by adding a single line of code.  Try doing a google search for "getbeaconparsers"
