### ISSUE TITLE
scan is null

### ISSUE THREAD

**Issue by vitas** [AltBeacon/android-beacon-library-reference#15]
Hi,
I cannot get this reference app working with my motorola device on 4.4.4
i have set debug mode and getting

10-29 13:39:18.006 30699-30699/org.altbeacon.beaconreference I/BeaconService: binding
10-29 13:39:18.225 30699-30699/org.altbeacon.beaconreference D/OpenGLRenderer: Enabling debug mode 0
10-29 13:39:18.233 30699-30699/org.altbeacon.beaconreference D/BeaconManager: we have a connection to the service now
10-29 13:39:18.233 30699-30699/org.altbeacon.beaconreference D/AppStarter: Activating background region monitoring
10-29 13:39:18.241 30699-30699/org.altbeacon.beaconreference D/AppStarter: Background region monitoring activated for region id1: null id2: null id3: null
10-29 13:39:18.241 30699-30699/org.altbeacon.beaconreference D/BeaconManager: callback packageName: org.altbeacon.beaconreference
10-29 13:39:18.342 30699-30699/org.altbeacon.beaconreference I/BeaconService: start monitoring received
10-29 13:39:18.342 30699-30699/org.altbeacon.beaconreference D/BeaconService: startMonitoring called
10-29 13:39:18.342 30699-30699/org.altbeacon.beaconreference D/BeaconService: Currently monitoring 1 regions.
10-29 13:39:18.342 30699-30699/org.altbeacon.beaconreference D/CycledLeScanner: start called

10-29 13:40:25.475 30699-30699/org.altbeacon.beaconreference D/BluetoothAdapter: stopLeScan()
10-29 13:40:25.483 30699-30699/org.altbeacon.beaconreference D/CycledLeScanner: starting a new scan cycle
10-29 13:40:25.483 30699-30699/org.altbeacon.beaconreference D/CycledLeScanner: starting a new bluetooth le scan
10-29 13:40:25.491 30699-30699/org.altbeacon.beaconreference D/BluetoothAdapter: startLeScan(): null

i have tried few apps from google play and they can discover my beacons.
please, help to get it working. thanks

**Comment by davidgyoung** [comment]
For help getting a custom app working on your device, please open a question on Stackoverflow.com, as this forum is reserved for feature requests and reproducible bug reports with the library itself.   When you do, please also test if you beacon can be detected by the free [Locate](https://play.google.com/store/search?q=locate%20beacon) Android app which is based on the same library.

**Comment by vitas** [comment]
Locate finds my beacons just fine

**Comment by davidgyoung** [comment]
OK, please post a question on Stackoverflow, and I'll do what I can to help.
