### ISSUE TITLE
Not able to set the layout for Eddystone signal.

### ISSUE THREAD

**Issue by anubhaw2091** [AltBeacon/android-beacon-library-reference#16]
I tried adding the following piece to code to set the app to read eddystone signal. 

`beaconManager.getBeaconParsers().clear();
        beaconManager.getBeaconParsers().add(new BeaconParser().
              setBeaconLayout(BeaconParser.EDDYSTONE_UID_LAYOUT));`
You mentioned somewhere that calling` bind() `is not necessary as when we call `RegionBootstrap`, binding is already done. How can be configure it to read eddystone? 
It's able to detect altBeacon signals but eddystone UID. Am using locate app on my device to transmit the signal.

**Comment by davidgyoung** [comment]
@anubhaw2091, it sounds like you are on the right track based on your comment.  If there is a problem that you need help with, please open a question on stackoverflow.com and we will help there, as this forum is reserved for feature requests and reproducible bugs in the library itself.

**Comment by anubhaw2091** [comment]
Thanks david.
Link to the question : http://stackoverflow.com/questions/33707962/how-to-make-make-android-app-detect-eddystone-signal
