### ISSUE TITLE
Is it possible to get services/characteristics from a GATT-based device with this library?

### ISSUE THREAD

**Issue by javiermanzano** [AltBeacon/android-beacon-library-reference#18]
I've tried to do it with the new classes introduced in the new Android's API but this library seems easier to work with.

**Comment by davidgyoung** [comment]
For support questions on the library, please open questions on StackOverflow.com.  In this case, I believe there is already an answer here: http://stackoverflow.com/a/35758225/1461050

This forum is reserved for feature requests and bugs with the reference app.
