### ISSUE TITLE
Altbeacon Launching in the Background detection time issue

### ISSUE THREAD

**Issue by Dhrupal** [AltBeacon/android-beacon-library-reference#2]
If I detect ibeacons from activity by starting service its detecting ibeacons perfectly fine.

Now I want to start the same operation in background(STICKY service). I followed 
http://altbeacon.github.io/android-beacon-library/background_launching.html
document. It is detecting ibeacons but problem is with time. It is taking too long to detect. 

beaconManager.setBackgroundScanPeriod(1100l);
beaconManager.setBackgroundBetweenScanPeriod(1100l);

**Comment by davidgyoung** [comment]
With Android 5.0 the detection time has been sped up greatly (within a few seconds.)  On older operating systems, the detection time is up to five minutes with default settings.
