### ISSUE TITLE
implement in background

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library-reference#22]
i am not understating how to use altbeacon in background or when app is closed....i am using altbeacon library. for continuous detect in background  or detect after when app closed, should i need to implement background services for that? and i checked this sample app , when i closed app from background its not working..

**Comment by arpitjoshi08** [comment]
i have done this with myself using this
` beaconManager.setBackgroundScanPeriod(2000l);
        beaconManager.setBackgroundBetweenScanPeriod(2000l);
   ` its working.  thanks and if any suggestion for this tell me..and close this issue

**Comment by am2222** [comment]
I have the same issue.Does we need any background service?

**Comment by davidgyoung** [comment]
Please see the [documentation](http://altbeacon.github.io/android-beacon-library/documentation.html), which has several sections on background usage.

If you have more questions, please ask them on StackOverflow.com, as this forum is reserved for reporting problems with the reference application itself.
