### ISSUE TITLE
didEnterRegion calling many times

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library-reference#23]
in application class didEnterRegion calling many times . i used this code in didEnterRegion method of application class
        beaconManager.setRangeNotifier(new RangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(final Collection<Beacon> beacons, Region region) {
                     for (Beacon oneBeacon : beacons) {
                        if (oneBeacon.getId2() != null && oneBeacon.getId3() != null) {
                       }
                    }`
and also this  `  beaconManager.startRangingBeaconsInRegion(region);`
for get the detail of beacon . what should i do ?

**Comment by davidgyoung** [comment]
For questions on how to use this library, please open a new question on StackOverflow.com.   This forum is reserved for feature requests and reproducible bug reports with the library itself.
