### ISSUE TITLE
In didEnterRegion() I cannot find beacon's UUID and MAC address ? I want UUID and Mac address only one time when it is entered into region.

### ISSUE THREAD

**Issue by ghost** [AltBeacon/android-beacon-library-reference#24]

**Comment by am2222** [comment]
It seems it gets these parameters from Region that you have declared earlier, I need these parametes too,Is there any way to get them in  `didEnterRegion() `?

**Comment by davidgyoung** [comment]
Please ask general questions on how to use this library on StackOverflow.com, as this forum is reserved for issues with the reference application.  

Note also that there is an answer to this question here:  http://stackoverflow.com/questions/39849297/how-can-i-get-beacons-data-uuid-major-minor-in-didenterregion-in-altbeacon/39862717#39862717
