### ISSUE TITLE
Which beacons are compatible with this library?

### ISSUE THREAD

**Issue by pedrobagatin** [AltBeacon/android-beacon-library-reference#29]
I installed the demo program and ran it, however it couldn't find any nearby RECO beacons...
Does anybody have a list of the beacons that have been tested and worked fine so far please?

**Comment by davidgyoung** [comment]
I suspect the beacons are compatible if you simplify configure the proper beacon parser with he library:

http://stackoverflow.com/questions/25027983/is-this-the-correct-layout-to-detect-ibeacons-with-altbeacons-android-beacon-li

You can see a list of parser expressions for popular beacon formats here:

https://beaconlayout.wordpress.com
