### ISSUE TITLE
TimedBeaconSimulator does not work

### ISSUE THREAD

**Issue by IgorGanapolsky** [AltBeacon/android-beacon-library-reference#33]
Hello,
I am trying to use your TimeBeaconSimulator on my emulator, but it doesn't work.  It doesn't output anything on the screen, and Logcat shows this error:
>BeaconManager: This device does not support bluetooth LE.
07-31 13:48:24.299 3468-3468/org.altbeacon.beaconreference W/BeaconManager: Method invocation will be ignored.

Do you know how to fix this?

igor

**Comment by davidgyoung** [comment]
Hi, @IgorGanapolsky.  Happy to help.  Can you please post this question on StackOverflow.com?  That is the preferred forum for questions on how to use the library so we can devote this forum to bug fixes and feature requests.
