### ISSUE TITLE
The library does not really work on background...

### ISSUE THREAD

**Issue by georgeRCluj** [AltBeacon/android-beacon-library-reference#34]
I implemented as in the documentation using both service / or Application class. Is not working. Period.

**Comment by davidgyoung** [comment]
Sorry to hear you are having trouble, @georgeRCluj.  Don't be discouraged -- thousands of apps use this library, most of them detecting in the background.  

If you need help getting this working, I'd suggest starting with the reference application here: https://github.com/altbeacon/android-beacon-library-reference

it is already set up for background detection and modifying it as needed.

If you need help, please open a new question on StackOverflow.com, which is the preferred forum for assistance using this library.

**Comment by georgeRCluj** [comment]
David, I finally managed to use it in background with Application Class. I make all the calls from there and then through broadcast receivers communicate the beacons information with services.

Thank you!
