### ISSUE TITLE
Tackle new beacons

### ISSUE THREAD

**Issue by imsrgadich** [AltBeacon/android-beacon-library-reference#35]
Hi devs, I'm working with CSR 1010 beacons. My concern is I don't have the beacon byte layout. Is there anyway how I could read the beacon advertisement data and get the rssi value? 

Thanks in advance!

**Comment by davidgyoung** [comment]
While the library is not designed for reading arbitrary advertising packets, you can do so by using the following class:

https://altbeacon.github.io/android-beacon-library/javadoc/org/altbeacon/beacon/service/scanner/NonBeaconLeScanCallback.html

The `BluetoothDevice` object in the callback has the RSSI property you are looking for.

**Comment by imsrgadich** [comment]
@davidgyoung Thank you for the reply. How do I the RSSI values continuously for non-beacons just like we have for beacons ` Beacon firstBeacon = beacons.iterator().next();`. 
Can you please help with this. thank you.

**Comment by imsrgadich** [comment]
@davidgyoung So this is for reading non-LE beacons if I'm right? (I can say because my app reading one now). My CSR 1010 beacon is a LE beacon and not non-LE? Do we have anything for this? 
Or is this a bug in the package?

**Comment by davidgyoung** [comment]
This is only for reading Bluetooth Low Energy (BLE) beacons.  If you have a Bluetooth classic device (non-BLE) this library will not detect them.

**Comment by imsrgadich** [comment]
I'm sure. I was detecting a non-BLE device at my home. Because I don't have one at my house and I checked with another BLE scanner and it didn't detect any BLE device. I have another question, I've the advertisement data layout from BLE beacon, but still my app doesn't parse it. Does the android device prefix some extra data at the front? Am I missing something here?

Thank you again!
