### ISSUE TITLE
Not possible to launch beacon simulation on an Emulated device

### ISSUE THREAD

**Issue by konstantin-kiriushyn** [AltBeacon/android-beacon-library-reference#37]
As soon as all preparations, mentioned in the `TimedBeaconSimulator.java`, are completed it is still not possible to simulate a beacon recognition on the Emulator. 

> W/BeaconManager: This device does not support bluetooth LE.
W/BeaconManager: Method invocation will be ignored.
W/BeaconManager: This device does not support bluetooth LE.
W/BeaconManager: Method invocation will be ignored.
D/BackgroundPowerSaver: activity resumed: org.altbeacon.beaconreference.MonitoringActivity@74988a2 active activities: 1
D/EGL_emulation: eglMakeCurrent: 0x9f8852a0: ver 2 0 (tinfo 0x9f8831c0)
W/BeaconManager: This device does not support bluetooth LE.
W/BeaconManager: Method invocation will be ignored.

The reason for that - `BeaconManager.java` has an internal check for support of the BLE capabilities [isBleAvailable()](https://github.com/AltBeacon/android-beacon-library/blob/master/src/main/java/org/altbeacon/beacon/BeaconManager.java#L1178), which is invoked before every scanning operation. This method ignores all debug-related settings.

Edit: punctuation

**Comment by davidgyoung** [comment]
Thanks for this report.  I know those checks on isBleAvailable() we're added after the simulator was added, so they must have broken the simulator functionality.

To fix it we need to replace the isBleAvailable() call with something like isBleAvailableOrSimulatorEnabled()

**Comment by davidgyoung** [comment]
This is fixed in the latest release 2.15.2
