### ISSUE TITLE
Beacon is not scanned after sometime in device running on android 7.1

### ISSUE THREAD

**Issue by adityasonel** [AltBeacon/android-beacon-library-reference#39]
I am developing an application with AltBeacon library, while I am debugging application. I don't what is happening but after sometimes it automatically stops beacon scanning. Then I have to switch restart device to make it working again. My device is Redmi 4A running on MIUI 9.1 (with Android 7.1).

**Comment by davidgyoung** [comment]
This kind of problem typically indicates an issue bluetooth stack on the Android device getting into a bad state.  Sometimes this can be recovered by cycling power to bluetooth.  There is a new library feature that can automatically do this described here:  https://github.com/AltBeacon/android-beacon-library/pull/644, but it is not in a formal release yet.  If you have comments on this, please discuss in that thread.
