### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by benju69** [AltBeacon/android-beacon-library-reference#4]
Application is not working at all, Ranging display nothing, the collection of beacons in didRangeBeaconsInRegion is empty

**Comment by davidgyoung** [comment]
@benju69, for library support, please create a question on Stackoverflow.com.  this forum us reserved for feature requests and reproducable bugs with the library.

Please also add more details including your device model, OS version, what kinds of beacons are transmitting (are the iBeacons, AltBeacons or other?)

**Comment by benju69** [comment]
My bad, sorry, it's iBeacons, I fix my problem with a beaconlayout like this : 
beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"));
http://stackoverflow.com/questions/25319682/correct-layout-to-detect-kontakt-beacon-on-android-with-altbeacon

**Comment by davidgyoung** [comment]
Glad you solved it.  Apologies, I has to redact the iBeacon layout string above.  Because it is proprietary info, we cannot disclose it inside the open source library or in its forums.

**Comment by benju69** [comment]
Ok, I understand
