### ISSUE TITLE
getting different manufacturer data.

### ISSUE THREAD

**Issue by jprashant610** [AltBeacon/android-beacon-library-reference#43]
Hello @davidgyoung , i have integrated the altBeacon library in my android application. It's working fine but i didn't received the proper manufacturer data when my application is in monitoring mode. I am using some reference application for example BLEScanner, BlueLoupe etc. I get the different manufacture data in my application than this reference applications. I have use the following code to get manufacture data.

```
 @Override
    public void onBeaconServiceConnect() {
        beaconManager.setRangeNotifier(new RangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(Collection<Beacon> beacons, Region region) {

                Log.e(TAG,"onBeaconServiceConnect()");

                if (beacons.size() > 0) {
                    Beacon firstBeacon = beacons.iterator().next();
                    Log.e(TAG,"Beacon Address:"+firstBeacon.getBluetoothAddress());
                    Log.e(TAG,"Beacon TxPower:"+firstBeacon.getTxPower());
                    Log.e(TAG,"Beacon Manufacturer:"+firstBeacon.getManufacturer());
                }
            }

        });

        try {
            beaconManager.startRangingBeaconsInRegion(new Region("myRangingUniqueId", null, null, null));
        } catch (RemoteException e) {   }
    }
```
How can i achieve the exact manufacturing data ?

**Comment by davidgyoung** [comment]
The code to get the manufacturer is correct.  I believe the manufacturer you see is what the bluetooth advertisement is sending.
