### ISSUE TITLE
Question: execution of code in a different thread

### ISSUE THREAD

**Issue by acutetech** [AltBeacon/android-beacon-library-reference#50]
This question is somewhat out of scope, but might be a "typical use" scenario, so perhaps you can offer insight or advice?

I am using Android Beacon Library to detect BLE devices, and it appears to do this very well: my app sees the beacon quickly, regardless of the state of the app or device. My problem is what happens next: I am using the [sync-android](https://github.com/cloudant/sync-android) library to send observations to a CouchDB database (rather: store a document locally then start a replication to a remote database, using HTTP). When the app is active the replication happens immediately, but when the phone has been idle for a time the replication takes a long time: 10s of minutes. So while the Android Beacon Library is doing what it should, my performance is being clobbered by the next library in the chain.

The sync-android documentation for Replicator.start() says "start will spawn a manager thread for the replication and immediately return." So perhaps the long latency is because Android OS is not scheduling that thread to run? Or could it be with the network parts of the OS? I'm running Android 7.

Any insights into what might be going on, and strategies? 

Thx - Charles

**Comment by davidgyoung** [comment]
The library uses a fix-sized thread pool to process beacon scans, and it is from this thread pool that callbacks are made to didRangeBeaconsInRegion, didEnterRegion, etc.  

In general, you should not execute long running code on these callback threads or you can exhaust them blocking further detections.  From the documentation you describe, it sounds like sync-android library  is spawning its own threads which may make this OK.

I can't speak as to why sync-android is not doing its processing right away.  It may not be that the thread is blocked, it may be that it schedules the updates to go in batches (perhaps using the JobScheduler or some similar mechanism.)

I would suggest you try troubleshooting this *outside* the context of beacon callbacks, as they just muddy the waters.  For testing, you might just run a timer to run every X seconds that triggers a sync-android update.  Do you see the same symptoms there?
