### ISSUE TITLE
didRangeBeaconsInRegion - trouble getting all beacons seen

### ISSUE THREAD

**Issue by datatribe** [AltBeacon/android-beacon-library-reference#58]
Starting with the reference app and working through my own requirements to make a service out of RangingActivity, I have discovered that the beacons Collection provided into didRangeBeaconsInRegion is having trouble when I try to iterate over it.  Often it throws an Invalid index exception.  I thought maybe this was an issue with the collection being updated too often so that by the time I start iterating, beacons.next() is not a valid pointer.  With that assumption, I attempted a work around by serializing the collection through a ObjectOutputStream to a ByteArrayOutputStream and then back to a collection via a ByteArrayInputStream and ObjectInputStream.  However, this seemed to suffer from the same problem.

My goal is to capture all of the beacons seen, gather some data about them and put that into a managed list so that I can transmit it to the server periodically.

```
@Override
    public void onBeaconServiceConnect() {
        Log.d(TAG,"Beacon Service Connect...");
        RangeNotifier rangeNotifier = new RangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(Collection<Beacon> beacons, Region region) {
                Log.d(TAG, "rangeNotifier sees " + beacons.size() + " beacons.");

 if (beacons != null && beacons.size() > 0) {

                        Log.d(TAG, "didRangeBeaconsInRegion called with beacon count:  " + beacons.size());
                        Iterator<Beacon> itt = beacons.iterator();
                        while(itt.hasNext()){
                            Beacon firstBeacon = itt.next();
                            if(firstBeacon!=null) {
                                try {
// exception throws from this line
                                    int keyCheck = firstBeacon.getId3().toInt();
// beaconList is my unique list of seen beacons
                                    if (beaconList.containsKey(String.valueOf(keyCheck))) {
                                        Log.d(TAG, "Beacon already found, not adding to temp list");
                                    } else {
                                        Log.d(TAG, "The beacon " + firstBeacon.toString() + " is about " + firstBeacon.getDistance() + " meters away.");
                                        Log.d(TAG, "Beacon Data: " + firstBeacon.getRssi());
                                        Log.d(TAG, "JSON data: " + mapData(firstBeacon));
                                        beaconList.put(firstBeacon.getId3().toString(), firstBeacon.getRssi() + "~" + firstBeacon.getDistance());
                                    }
                                } catch (IndexOutOfBoundsException e) {
// I wind up seeing this log statement often with the message Invalid index 2, size is 1 (or 2...)
                                    Log.e(TAG, "Object not ready or tried to access next object before ready on beacons collection. " + e.getLocalizedMessage());
                                }
                            }
                        }

};
        try {
            beaconManager.startRangingBeaconsInRegion(new Region("myRangingUniqueId", null, null, null));
            beaconManager.addRangeNotifier(rangeNotifier);
            beaconManager.startRangingBeaconsInRegion(new Region("myRangingUniqueId", null, null, null));
            beaconManager.addRangeNotifier(rangeNotifier);
        } catch (RemoteException e) {
            Log.e(TAG, e.getLocalizedMessage());
        }
    }
```

Is there a possibility that the reference code could be updated to include a working example of iterating over or otherwise consuming the data from every beacon in Collection<Beacon> beacons, or is there some other way to accomplish this?

**Comment by davidgyoung** [comment]
This really should be easy!  Check out the example of iterating over the Beacon collection here: https://altbeacon.github.io/android-beacon-library/distance-triggering.html

I promise that works -- I use it all the time!

If you need more assistance, please open a question on StackOverflow.

**Comment by datatribe** [comment]
Oh, I agree it should be easy.  I tried many forms of For loop on the beacons collection, including the one you suggested, and the problem seems to remain.  I am beginning to think it may have to do with converting the RangingActivity to a service.  I wanted this to run in the background independent of the UI, but as the MonitoringActivity is what fires off this service onCreate, I might be stepping on some threads at runtime causing the problems which seem to be pointer related.  Thanks for the additional sample, though - it confirmed for me that the problem is not in the loop or the beacon collection itself.

**Comment by datatribe** [comment]
Oh, this might be part of the problem.  Some of my beacons apparently lack mIdentifiers[2].  The problem seems to stem from this line of code in the Beacon.class, not with the way I'm launching the service (a surprise to me).

```
public Identifier getId3() {
        return (Identifier)this.mIdentifiers.get(2);
    }
```
Adding a check before trying to access getId3 seems to solve the problem.

```
if(beacon.getIdentifiers().size()>2) {
    // safely check getId3()
}
```

I guess the conversation is now academic as to whether this is something that getId3() should fail gracefully on or not.
