### ISSUE TITLE
Crash onResume

### ISSUE THREAD

**Issue by dkeydevs** [AltBeacon/android-beacon-library-reference#60]
Hi there, 
my devices crash with the following error:

```
Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to myapp.beaconreference.BeaconReferenceApplication
        at myapp.beaconreference.MonitoringActivity.onResume(MonitoringActivity.java:169)     
```  

where 169 is this line here:
```
BeaconReferenceApplication application = ((BeaconReferenceApplication) this.getApplicationContext());
        application.setMonitoringActivity(this);
        updateLog(application.getLog());
```

quoting out the line above, it crashes on the onPause:

`(BeaconReferenceApplication) this.getApplicationContext()).setMonitoringActivity(null);`

**Comment by davidgyoung** [comment]
It appears that you have modified the package name of the reference application to be "myapp.beaconreference" from "org.altbeacon.beaconreference".  This will cause problems if you don't make other changes:


Please check your AndroidManifest.xml and make sure that:

1.  Your <manifest> element sets package="org.altbeacon.beaconreference" (if this is not true see step 3.)
2. The <application> element sets android:name="BeaconReferenceApplication"
3. The java package of BeaconReferenceApplication.java matches the package in (1)
