### ISSUE TITLE
Parse every beacon

### ISSUE THREAD

**Issue by axierjhtjz** [AltBeacon/android-beacon-library-reference#7]
As said in the documentation you can add a BeaconLayout to the BeaconParser list adding a string with the beacon specification. Is there a way to parse every beacon without declaring a scheme?

Thanks!

**Comment by davidgyoung** [comment]
The library must know about a beacon layout in order to parse it.  New beacon types are invented all the time, and it is impossible to imagine every beacon layout folks can come up with.  This is why declaration is required.
