### ISSUE TITLE
Reference implementation risks leaking activity context

### ISSUE THREAD

**Issue by samskiter** [AltBeacon/android-beacon-library-reference#8]
This is either a problem in the reference code or in the library, but the following line risks leaking an activity via passing a context

https://github.com/AltBeacon/android-beacon-library-reference/blob/master/app/src/main/java/org/altbeacon/beaconreference/RangingActivity.java#L22

It's only because the singleton is accessed from the application object first that the context passed here is not retained/leaked.

I'll also add a bug to the main library and let you decide whether the getInstanceForApplication should mandate it is passed an application context, or ensures it has one itself.

**Comment by davidgyoung** [comment]
Fixed here: https://github.com/AltBeacon/android-beacon-library/pull/381
